In [1]:
import pandas as pd

In [5]:
my_list = [10,20,30,40]
labels= ['a','b','c','d']
df=pd.Series(my_list,index=labels)
df

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
data = {
    'name':["ram","shyam","hari","gita"],
    "age":[10,20,22,12],
    "Salary":[2000,4000,2000,4000]
}
df = pd.DataFrame(data)

df

    name  age  Salary
0    ram   10    2000
1  shyam   20    4000
2   hari   22    2000
3   gita   12    4000

In [18]:
data1 = [
    ["ram",20],
    ['shyam',400]
]
label = ['name','age']
df2 = pd.DataFrame(data1,columns=label)
df2

    name  age
0    ram   20
1  shyam  400

In [51]:
df
df['name']
df[['name','age']]
df['city']=["ktm",'pkr','ktm','btw']
df
# df.drop('Salary', axis=1)
df
# df.drop('Salary', axis=1,inplace=True)
df
df.loc[0]
df.loc[[0,2],['name']]
df[(df['age']>10)&(df['city']=='ktm')]

   name  age city
2  hari   22  ktm