In [23]:
import pandas as pd 
data = {
    "name": ["Ram", "Sita", "Hari", "Gita", "John", "Ram"],
    "age": [22, None, 25, 17, 30, 22],
    "salary": [30000, 25000, None, 20000, 60000, 30000],
    "city": ["Kathmandu", "Pokhara", "Kathmandu", None, "Bhaktapur", "Kathmandu"]
}

df = pd.DataFrame(data)

In [24]:
df.isna()

    name    age  salary   city
0  False  False   False  False
1  False   True   False  False
2  False  False    True  False
3  False  False   False   True
4  False  False   False  False
5  False  False   False  False

In [25]:
df.isna().sum()

name      0
age       1
salary    1
city      1
dtype: int64

In [26]:
df.dropna()

   name   age   salary       city
0   Ram  22.0  30000.0  Kathmandu
4  John  30.0  60000.0  Bhaktapur
5   Ram  22.0  30000.0  Kathmandu

In [27]:
df['age']=df['age'].fillna(df['age'].mean())
df

   name   age   salary       city
0   Ram  22.0  30000.0  Kathmandu
1  Sita  23.2  25000.0    Pokhara
2  Hari  25.0      NaN  Kathmandu
3  Gita  17.0  20000.0        NaN
4  John  30.0  60000.0  Bhaktapur
5   Ram  22.0  30000.0  Kathmandu

In [28]:
df['salary']=df['salary'].fillna(0)
df

   name   age   salary       city
0   Ram  22.0  30000.0  Kathmandu
1  Sita  23.2  25000.0    Pokhara
2  Hari  25.0      0.0  Kathmandu
3  Gita  17.0  20000.0        NaN
4  John  30.0  60000.0  Bhaktapur
5   Ram  22.0  30000.0  Kathmandu

In [29]:
df['city']=df['city'].fillna("Unknown")
df

   name   age   salary       city
0   Ram  22.0  30000.0  Kathmandu
1  Sita  23.2  25000.0    Pokhara
2  Hari  25.0      0.0  Kathmandu
3  Gita  17.0  20000.0    Unknown
4  John  30.0  60000.0  Bhaktapur
5   Ram  22.0  30000.0  Kathmandu

In [30]:
df.drop_duplicates()

   name   age   salary       city
0   Ram  22.0  30000.0  Kathmandu
1  Sita  23.2  25000.0    Pokhara
2  Hari  25.0      0.0  Kathmandu
3  Gita  17.0  20000.0    Unknown
4  John  30.0  60000.0  Bhaktapur

In [33]:
df.rename(columns={"salary":"monthly_salary"},inplace=True)

In [40]:
df.dtypes
df['monthly_salary']=df['monthly_salary'].astype(int)

In [43]:
df['annual_salary']=df['monthly_salary']*12
df

   name   age  monthly_salary       city  annual_salary
0   Ram  22.0           30000  Kathmandu         360000
1  Sita  23.2           25000    Pokhara         300000
2  Hari  25.0               0  Kathmandu              0
3  Gita  17.0           20000    Unknown         240000
4  John  30.0           60000  Bhaktapur         720000
5   Ram  22.0           30000  Kathmandu         360000