In [2]:
import pandas as pd 

data = {
    "name": ["Ram", "Sita", "Hari", "Gita", "John"],
    "age": [22, 19, 25, 17, 30],
    "city": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur", "Bhaktapur"],
    "salary": [30000, 25000, 45000, 20000, 60000]
    
}

df = pd.DataFrame(data)

In [3]:
df

   name  age       city  salary
0   Ram   22  Kathmandu   30000
1  Sita   19    Pokhara   25000
2  Hari   25  Kathmandu   45000
3  Gita   17   Lalitpur   20000
4  John   30  Bhaktapur   60000

In [4]:
df.head(3)

   name  age       city  salary
0   Ram   22  Kathmandu   30000
1  Sita   19    Pokhara   25000
2  Hari   25  Kathmandu   45000

In [5]:
df.tail(2)

   name  age       city  salary
3  Gita   17   Lalitpur   20000
4  John   30  Bhaktapur   60000

In [6]:
df.shape

(5, 4)

In [7]:
df.columns

Index(['name', 'age', 'city', 'salary'], dtype='str')

In [9]:
df.dtypes

name        str
age       int64
city        str
salary    int64
dtype: object

In [10]:
df['name']

0     Ram
1    Sita
2    Hari
3    Gita
4    John
Name: name, dtype: str

In [11]:
df[['name','salary']]

   name  salary
0   Ram   30000
1  Sita   25000
2  Hari   45000
3  Gita   20000
4  John   60000

In [18]:
df[df['age']>20]
df[df['salary']>30000]['name']

2    Hari
4    John
Name: name, dtype: str

In [20]:
df[df['city']=="Kathmandu"]['name']

0     Ram
2    Hari
Name: name, dtype: str

In [23]:
df[(df['age']>20) & (df['age']<30)]

   name  age       city  salary
0   Ram   22  Kathmandu   30000
2  Hari   25  Kathmandu   45000

In [27]:
df.sort_values(by='salary' ,ascending=False)

   name  age       city  salary
4  John   30  Bhaktapur   60000
2  Hari   25  Kathmandu   45000
0   Ram   22  Kathmandu   30000
1  Sita   19    Pokhara   25000
3  Gita   17   Lalitpur   20000

In [31]:

df['salary'].mean()

36000.0

In [32]:
df['salary'].max()

60000

In [34]:
df['salary'].min()

20000

In [36]:
df['salary'].sum()

180000

In [41]:
df.groupby('city').size()

city
Bhaktapur    1
Kathmandu    2
Lalitpur     1
Pokhara      1
dtype: int64